apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: lojtr8yuk-python 
  janus-idp.io/tekton: lojtr8yuk-python
  backstage.io/kubernetes-id: lojtr8yuk-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lojtr8yuk-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml