apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lojtr8yuk-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lojtr8yuk-python 
  name: lojtr8yuk-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: lojtr8yuk-python 
